/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apiclientdesktop;

import com.sun.org.apache.bcel.internal.generic.JsrInstruction;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLEncoder;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.jsoup.Jsoup;
import org.jsoup.nodes.*;

/**
 *
 * @author Asus
 */
public class ApiJFrame extends javax.swing.JFrame {

    DataHandler dh = new DataHandler();

    /**
     * Creates new form ApiJFrame
     */
    public ApiJFrame() {
        initComponents();
        loadData();
        tableSettings();
        MainPanel.setViewportView(ProvinsiPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProvinsiPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProvinsiTable = new javax.swing.JTable();
        ProvinsiButtonBack = new javax.swing.JButton();
        ProvinsiButtonEdit = new javax.swing.JButton();
        ProvinsiButtonDelete = new javax.swing.JButton();
        ProvinsiButtonAdd = new javax.swing.JButton();
        ProvinsiEditPanel = new javax.swing.JPanel();
        ProvinsiEditButtonBack = new javax.swing.JButton();
        ProvinsiEditButtonSave = new javax.swing.JButton();
        ProvinsiEditNameTf = new javax.swing.JTextField();
        ProvinsiEditIdLabel = new javax.swing.JLabel();
        ProvinsiEditId = new javax.swing.JLabel();
        ProvinsiEditNameLabel = new javax.swing.JLabel();
        ProvinsiEditPopulationsLabel = new javax.swing.JLabel();
        ProvinsiEditPopulationsTf = new javax.swing.JTextField();
        ProvinsiEditIdWeatherLabel = new javax.swing.JLabel();
        ProvinsiEditIdWeatherTf = new javax.swing.JTextField();
        ProvinsiEditErrorName = new javax.swing.JLabel();
        ProvinsiAddPanel = new javax.swing.JPanel();
        ProvinsiAddButtonSave = new javax.swing.JButton();
        ProvinsiAddButtonBack = new javax.swing.JButton();
        ProvinsiAddIdLabel = new javax.swing.JLabel();
        ProvinsiAddIdTf = new javax.swing.JTextField();
        ProvinsiAddErrorLabelId = new javax.swing.JLabel();
        ProvinsiAddNameLabel = new javax.swing.JLabel();
        ProvinsiAddNametf = new javax.swing.JTextField();
        ProvinsiAddErrorLabelName = new javax.swing.JLabel();
        ProvinsiAddPopulationTf = new javax.swing.JTextField();
        ProvinsiAddPopulationLabel = new javax.swing.JLabel();
        ProvinsiAddIdWeatherLabel = new javax.swing.JLabel();
        ProvinsiAddIdWeatherTf = new javax.swing.JTextField();
        DashboardPanel = new javax.swing.JPanel();
        MainPanel = new javax.swing.JScrollPane();

        ProvinsiPanel.setBackground(new java.awt.Color(102, 102, 102));

        ProvinsiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Populations", "Id_Weather"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProvinsiTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProvinsiTable.setFocusable(false);
        ProvinsiTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ProvinsiTable.setSelectionBackground(new java.awt.Color(32, 136, 203));
        ProvinsiTable.getTableHeader().setResizingAllowed(false);
        ProvinsiTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ProvinsiTable);
        if (ProvinsiTable.getColumnModel().getColumnCount() > 0) {
            ProvinsiTable.getColumnModel().getColumn(0).setResizable(false);
            ProvinsiTable.getColumnModel().getColumn(1).setResizable(false);
            ProvinsiTable.getColumnModel().getColumn(2).setResizable(false);
            ProvinsiTable.getColumnModel().getColumn(3).setResizable(false);
        }

        ProvinsiButtonBack.setBackground(new java.awt.Color(153, 153, 0));
        ProvinsiButtonBack.setFont(new java.awt.Font("Raleway", 1, 11)); // NOI18N
        ProvinsiButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiButtonBack.setText("Kembali");

        ProvinsiButtonEdit.setBackground(new java.awt.Color(255, 153, 51));
        ProvinsiButtonEdit.setFont(new java.awt.Font("Raleway", 1, 11)); // NOI18N
        ProvinsiButtonEdit.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiButtonEdit.setText("Edit");
        ProvinsiButtonEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProvinsiButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvinsiButtonEditActionPerformed(evt);
            }
        });

        ProvinsiButtonDelete.setBackground(new java.awt.Color(204, 0, 0));
        ProvinsiButtonDelete.setFont(new java.awt.Font("Raleway", 1, 11)); // NOI18N
        ProvinsiButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiButtonDelete.setText("Hapus");
        ProvinsiButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProvinsiButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvinsiButtonDeleteActionPerformed(evt);
            }
        });

        ProvinsiButtonAdd.setBackground(new java.awt.Color(0, 153, 0));
        ProvinsiButtonAdd.setFont(new java.awt.Font("Raleway", 1, 11)); // NOI18N
        ProvinsiButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiButtonAdd.setText("Tambah");
        ProvinsiButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvinsiButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProvinsiPanelLayout = new javax.swing.GroupLayout(ProvinsiPanel);
        ProvinsiPanel.setLayout(ProvinsiPanelLayout);
        ProvinsiPanelLayout.setHorizontalGroup(
            ProvinsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProvinsiPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ProvinsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProvinsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProvinsiPanelLayout.createSequentialGroup()
                        .addComponent(ProvinsiButtonBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProvinsiPanelLayout.createSequentialGroup()
                        .addComponent(ProvinsiButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProvinsiButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProvinsiButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ProvinsiPanelLayout.setVerticalGroup(
            ProvinsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProvinsiPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProvinsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProvinsiButtonEdit)
                    .addComponent(ProvinsiButtonDelete)
                    .addComponent(ProvinsiButtonAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(ProvinsiButtonBack)
                .addContainerGap())
        );

        ProvinsiEditPanel.setBackground(new java.awt.Color(102, 102, 102));

        ProvinsiEditButtonBack.setBackground(new java.awt.Color(153, 153, 0));
        ProvinsiEditButtonBack.setFont(new java.awt.Font("Raleway", 1, 11)); // NOI18N
        ProvinsiEditButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiEditButtonBack.setText("Kembali");
        ProvinsiEditButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvinsiEditButtonBackActionPerformed(evt);
            }
        });

        ProvinsiEditButtonSave.setBackground(new java.awt.Color(0, 153, 0));
        ProvinsiEditButtonSave.setFont(new java.awt.Font("Raleway", 1, 11)); // NOI18N
        ProvinsiEditButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiEditButtonSave.setText("Simpan");
        ProvinsiEditButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvinsiEditButtonSaveActionPerformed(evt);
            }
        });

        ProvinsiEditIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiEditIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiEditIdLabel.setText("Id Provinsi :");

        ProvinsiEditId.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiEditId.setForeground(new java.awt.Color(255, 255, 255));

        ProvinsiEditNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiEditNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiEditNameLabel.setText("Nama Provinsi :");

        ProvinsiEditPopulationsLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiEditPopulationsLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiEditPopulationsLabel.setText("Populations        :");

        ProvinsiEditIdWeatherLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiEditIdWeatherLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiEditIdWeatherLabel.setText("Id Weather (OpenWeather Id) :");

        ProvinsiEditErrorName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiEditErrorName.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout ProvinsiEditPanelLayout = new javax.swing.GroupLayout(ProvinsiEditPanel);
        ProvinsiEditPanel.setLayout(ProvinsiEditPanelLayout);
        ProvinsiEditPanelLayout.setHorizontalGroup(
            ProvinsiEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProvinsiEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProvinsiEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProvinsiEditPanelLayout.createSequentialGroup()
                        .addGroup(ProvinsiEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProvinsiEditButtonBack)
                            .addComponent(ProvinsiEditButtonSave)
                            .addGroup(ProvinsiEditPanelLayout.createSequentialGroup()
                                .addComponent(ProvinsiEditIdLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProvinsiEditId))
                            .addComponent(ProvinsiEditNameLabel)
                            .addComponent(ProvinsiEditPopulationsLabel))
                        .addGap(497, 850, Short.MAX_VALUE))
                    .addGroup(ProvinsiEditPanelLayout.createSequentialGroup()
                        .addGroup(ProvinsiEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProvinsiEditPanelLayout.createSequentialGroup()
                                .addComponent(ProvinsiEditNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProvinsiEditErrorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ProvinsiEditPanelLayout.createSequentialGroup()
                                .addGroup(ProvinsiEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ProvinsiEditIdWeatherTf, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProvinsiEditPopulationsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProvinsiEditIdWeatherLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
        );
        ProvinsiEditPanelLayout.setVerticalGroup(
            ProvinsiEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProvinsiEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProvinsiEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProvinsiEditIdLabel)
                    .addComponent(ProvinsiEditId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProvinsiEditNameLabel)
                .addGap(1, 1, 1)
                .addGroup(ProvinsiEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProvinsiEditErrorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProvinsiEditNameTf, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(ProvinsiEditPopulationsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProvinsiEditPopulationsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ProvinsiEditIdWeatherLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProvinsiEditIdWeatherTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(ProvinsiEditButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(ProvinsiEditButtonBack)
                .addContainerGap())
        );

        ProvinsiAddPanel.setBackground(new java.awt.Color(102, 102, 102));

        ProvinsiAddButtonSave.setBackground(new java.awt.Color(0, 153, 0));
        ProvinsiAddButtonSave.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiAddButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiAddButtonSave.setText("Simpan");
        ProvinsiAddButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvinsiAddButtonSaveActionPerformed(evt);
            }
        });

        ProvinsiAddButtonBack.setBackground(new java.awt.Color(0, 51, 153));
        ProvinsiAddButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiAddButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiAddButtonBack.setText("Kembali");
        ProvinsiAddButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvinsiAddButtonBackActionPerformed(evt);
            }
        });

        ProvinsiAddIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiAddIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiAddIdLabel.setLabelFor(ProvinsiAddIdTf);
        ProvinsiAddIdLabel.setText("Id Provinsi :");

        ProvinsiAddErrorLabelId.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiAddErrorLabelId.setForeground(new java.awt.Color(204, 0, 0));

        ProvinsiAddNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiAddNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiAddNameLabel.setLabelFor(ProvinsiAddNametf);
        ProvinsiAddNameLabel.setText("Nama Provinsi :");

        ProvinsiAddErrorLabelName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiAddErrorLabelName.setForeground(new java.awt.Color(204, 0, 0));

        ProvinsiAddPopulationLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiAddPopulationLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiAddPopulationLabel.setLabelFor(ProvinsiAddPopulationTf);
        ProvinsiAddPopulationLabel.setText("Populasi :");

        ProvinsiAddIdWeatherLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ProvinsiAddIdWeatherLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProvinsiAddIdWeatherLabel.setLabelFor(ProvinsiAddIdWeatherTf);
        ProvinsiAddIdWeatherLabel.setText("Id Weather (OpenWeather Id) :");

        javax.swing.GroupLayout ProvinsiAddPanelLayout = new javax.swing.GroupLayout(ProvinsiAddPanel);
        ProvinsiAddPanel.setLayout(ProvinsiAddPanelLayout);
        ProvinsiAddPanelLayout.setHorizontalGroup(
            ProvinsiAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProvinsiAddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProvinsiAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProvinsiAddPanelLayout.createSequentialGroup()
                        .addComponent(ProvinsiAddIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProvinsiAddErrorLabelId, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
                    .addGroup(ProvinsiAddPanelLayout.createSequentialGroup()
                        .addGroup(ProvinsiAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProvinsiAddNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProvinsiAddNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProvinsiAddErrorLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ProvinsiAddPanelLayout.createSequentialGroup()
                        .addGroup(ProvinsiAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProvinsiAddPopulationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProvinsiAddButtonBack)
                            .addComponent(ProvinsiAddButtonSave)
                            .addComponent(ProvinsiAddIdLabel)
                            .addComponent(ProvinsiAddPopulationLabel)
                            .addComponent(ProvinsiAddIdWeatherTf, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProvinsiAddIdWeatherLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ProvinsiAddPanelLayout.setVerticalGroup(
            ProvinsiAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProvinsiAddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProvinsiAddIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProvinsiAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProvinsiAddIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProvinsiAddErrorLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProvinsiAddNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProvinsiAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProvinsiAddErrorLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProvinsiAddNametf, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProvinsiAddPopulationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProvinsiAddPopulationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(ProvinsiAddIdWeatherLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProvinsiAddIdWeatherTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProvinsiAddButtonSave)
                .addGap(60, 60, 60)
                .addComponent(ProvinsiAddButtonBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout DashboardPanelLayout = new javax.swing.GroupLayout(DashboardPanel);
        DashboardPanel.setLayout(DashboardPanelLayout);
        DashboardPanelLayout.setHorizontalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        DashboardPanelLayout.setVerticalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Editor for API Data Indonesia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProvinsiButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvinsiButtonEditActionPerformed
        int i = ProvinsiTable.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin di edit!", "Gagal!", JOptionPane.WARNING_MESSAGE);
        } else {
            String idprov = ProvinsiTable.getValueAt(i, 0).toString();
            Provinsi prov = dh.getProvinsi(idprov);
            ProvinsiEditId.setText(prov.getId());
            ProvinsiEditNameTf.setText(prov.getName());
            ProvinsiEditPopulationsTf.setText(String.valueOf(prov.getPopulations()));
            ProvinsiEditIdWeatherTf.setText(prov.getId_weather());
            MainPanel.setViewportView(ProvinsiEditPanel);
        }
    }//GEN-LAST:event_ProvinsiButtonEditActionPerformed

    private void ProvinsiEditButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvinsiEditButtonBackActionPerformed
        clearData();
        loadData();
        tableSettings();
        MainPanel.setViewportView(ProvinsiPanel);
    }//GEN-LAST:event_ProvinsiEditButtonBackActionPerformed

    private void ProvinsiButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvinsiButtonAddActionPerformed
        MainPanel.setViewportView(ProvinsiAddPanel);
    }//GEN-LAST:event_ProvinsiButtonAddActionPerformed

    private void ProvinsiAddButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvinsiAddButtonSaveActionPerformed
        String idprov = ProvinsiAddIdTf.getText(), name = ProvinsiAddNametf.getText(), idweather = ProvinsiAddIdWeatherTf.getText();
        int pop = 0;
        if (!ProvinsiAddPopulationTf.getText().equals("")) {
            pop = Integer.parseInt(ProvinsiAddPopulationTf.getText());
        }
        String mesg = dh.addProvinsi(idprov, name, pop, idweather);
        if (mesg.contains("Sukses!")) {
            String[] values = mesg.split("! ");
            JOptionPane.showMessageDialog(this, values[1] + "!", values[0] + "!", JOptionPane.INFORMATION_MESSAGE);
            clearError();
            clearForm();
        } else {
            String[] values = mesg.split("! ");
            if (values.length > 1) {
                if (!values[1].contains("Kode") && !values[0].contains("Nama")) {
                    clearError();
                    ProvinsiAddErrorLabelId.setText(values[0] + "!");
                    ProvinsiAddErrorLabelName.setText(values[1] + "!");
                }
            } else {
                if (values[0].contains("Kode")) {
                    clearError();
                    ProvinsiAddErrorLabelName.setText("");
                    ProvinsiAddErrorLabelId.setText(values[0] + "!");
                } else {
                    clearError();
                    ProvinsiAddErrorLabelId.setText("");
                    ProvinsiAddErrorLabelName.setText(values[0] + "!");
                }
            }
        }
    }//GEN-LAST:event_ProvinsiAddButtonSaveActionPerformed

    private void ProvinsiAddButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvinsiAddButtonBackActionPerformed
        clearData();
        loadData();
        tableSettings();
        clearError();
        clearForm();
        MainPanel.setViewportView(ProvinsiPanel);
    }//GEN-LAST:event_ProvinsiAddButtonBackActionPerformed

    private void ProvinsiEditButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvinsiEditButtonSaveActionPerformed
        String id = ProvinsiEditId.getText(), name = ProvinsiEditNameTf.getText(), id_weath = ProvinsiEditIdWeatherTf.getText();
        int pop = 0;
        if (!ProvinsiEditPopulationsTf.getText().equals("")) {
            pop = Integer.parseInt(ProvinsiEditPopulationsTf.getText());
        }
        String mesg = dh.updateProvinsi(id, name, pop, id_weath);
        if (mesg.contains("Sukses!")) {
            String[] values = mesg.split("! ");
            JOptionPane.showMessageDialog(this, values[1] + "!", values[0] + "!", JOptionPane.INFORMATION_MESSAGE);
            clearError();
            clearForm();
        } else {
            String[] values = mesg.split("! ");
            if (values.length > 1) {
                if (!values[1].contains("Kode") && !values[0].contains("Nama")) {
                    clearError();
                    ProvinsiEditErrorName.setText(values[0] + "!");
                }
            } else {
                if (values[0].contains("Kode")) {
                    clearError();
                    ProvinsiAddErrorLabelId.setText(values[0] + "!");
                } else {
                    clearError();
                    ProvinsiEditErrorName.setText(values[0] + "!");
                }
            }
        }
    }//GEN-LAST:event_ProvinsiEditButtonSaveActionPerformed

    private void ProvinsiButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvinsiButtonDeleteActionPerformed
        int i = ProvinsiTable.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!", "Gagal!", JOptionPane.WARNING_MESSAGE);
        } else {
            String idprov = ProvinsiTable.getValueAt(i, 0).toString();
            String mesg = dh.deleteProvinsi(idprov);
            if (mesg.contains("Sukses!")) {
                String[] values = mesg.split("! ");
                JOptionPane.showMessageDialog(this, values[1] + "!", values[0] + "!", JOptionPane.INFORMATION_MESSAGE);
                clearData();
                loadData();
            } else {
                String[] values = mesg.split("! ");
                JOptionPane.showMessageDialog(this, values[0]+"!");
            }
        }
    }//GEN-LAST:event_ProvinsiButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApiJFrame().setVisible(true);
            }
        });
    }

    private void clearData() {
        DefaultTableModel provdm = (DefaultTableModel) ProvinsiTable.getModel();
        while (provdm.getRowCount() > 0) {
            provdm.removeRow(0);
        }
    }

    private void loadData() {
        DefaultTableModel provdm = (DefaultTableModel) ProvinsiTable.getModel();
        List<Provinsi> provinsi = dh.getAllProvinsi();
        for (int i = 0; i < provinsi.size(); i++) {
            provdm.addRow(new Object[]{
                provinsi.get(i).getId(),
                provinsi.get(i).getName(),
                provinsi.get(i).getPopulations(),
                provinsi.get(i).getId_weather()
            });
        }
    }

    private void tableSettings() {
        TableCellRenderer tcr = new TextTableCenter();

        //Table Provinsi
        JTableHeader headerprov = ProvinsiTable.getTableHeader();
        ProvinsiTable.setShowGrid(true);
        ProvinsiTable.getColumnModel().getColumn(0).setCellRenderer(tcr);
        ProvinsiTable.getColumnModel().getColumn(1).setCellRenderer(tcr);
        ProvinsiTable.getColumnModel().getColumn(2).setCellRenderer(tcr);
        ProvinsiTable.getColumnModel().getColumn(3).setCellRenderer(tcr);
        ProvinsiTable.setFont(new Font("Roboto", Font.BOLD, 11));
        ProvinsiTable.setRowHeight(25);
        ((DefaultTableCellRenderer) headerprov.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        ((DefaultTableCellRenderer) headerprov.getDefaultRenderer()).setFont(new Font("Segoe UI", Font.BOLD, 12));
        headerprov.setBackground(Color.blue);
        headerprov.setOpaque(true);

    }

    private void clearForm() {
        //Provinsi
        //Add
        ProvinsiAddIdTf.setText("");
        ProvinsiAddNametf.setText("");
        ProvinsiAddIdWeatherTf.setText("");
        ProvinsiAddPopulationTf.setText("");
        //Edit
        ProvinsiEditId.setText("");
        ProvinsiEditNameTf.setText("");
        ProvinsiEditPopulationsTf.setText("");
        ProvinsiEditIdWeatherTf.setText("");
    }

    private void clearError() {
        ProvinsiAddErrorLabelId.setText("");
        ProvinsiAddErrorLabelName.setText("");
        ProvinsiEditErrorName.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JScrollPane MainPanel;
    private javax.swing.JButton ProvinsiAddButtonBack;
    private javax.swing.JButton ProvinsiAddButtonSave;
    private javax.swing.JLabel ProvinsiAddErrorLabelId;
    private javax.swing.JLabel ProvinsiAddErrorLabelName;
    private javax.swing.JLabel ProvinsiAddIdLabel;
    private javax.swing.JTextField ProvinsiAddIdTf;
    private javax.swing.JLabel ProvinsiAddIdWeatherLabel;
    private javax.swing.JTextField ProvinsiAddIdWeatherTf;
    private javax.swing.JLabel ProvinsiAddNameLabel;
    private javax.swing.JTextField ProvinsiAddNametf;
    private javax.swing.JPanel ProvinsiAddPanel;
    private javax.swing.JLabel ProvinsiAddPopulationLabel;
    private javax.swing.JTextField ProvinsiAddPopulationTf;
    private javax.swing.JButton ProvinsiButtonAdd;
    private javax.swing.JButton ProvinsiButtonBack;
    private javax.swing.JButton ProvinsiButtonDelete;
    private javax.swing.JButton ProvinsiButtonEdit;
    private javax.swing.JButton ProvinsiEditButtonBack;
    private javax.swing.JButton ProvinsiEditButtonSave;
    private javax.swing.JLabel ProvinsiEditErrorName;
    private javax.swing.JLabel ProvinsiEditId;
    private javax.swing.JLabel ProvinsiEditIdLabel;
    private javax.swing.JLabel ProvinsiEditIdWeatherLabel;
    private javax.swing.JTextField ProvinsiEditIdWeatherTf;
    private javax.swing.JLabel ProvinsiEditNameLabel;
    private javax.swing.JTextField ProvinsiEditNameTf;
    private javax.swing.JPanel ProvinsiEditPanel;
    private javax.swing.JLabel ProvinsiEditPopulationsLabel;
    private javax.swing.JTextField ProvinsiEditPopulationsTf;
    private javax.swing.JPanel ProvinsiPanel;
    private javax.swing.JTable ProvinsiTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
